backend/account/urls.py
from django.urls import path
from account.views import ViewAccountLogin, ViewAccountSignup, ViewAccountLogout, ViewAccountDashboard

urlpatterns = [
    path("", ViewAccountLogin.as_view(), name="login"),
    path("signup/", ViewAccountSignup.as_view(), name="signup"),
    path("logout/", ViewAccountLogout.as_view(), name="logout"),
    path("dashboard/", ViewAccountDashboard.as_view(), name="dashboard"),
]

backend/backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('',
        include(('account.urls', 'account'), namespace='account')
    ),
    path('api/',
        include(('backend.api_urls', 'api'), namespace='api'),
    ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/post/urls.py
from django.urls import path

urlpatterns = [
    
]

backend/base/models.py
from django.db import models
from django.db.models.fields import DateTimeField


# -------------------------------------------------------------------------------
# ModelAbstractBase
# -------------------------------------------------------------------------------
class ModelAbstractBase(models.Model):
    """
    Abstract base model.
    """

    created = DateTimeField(
        auto_now_add=True,
        help_text="Date and time when this entry was created in the system"
    )

    updated = DateTimeField(
        auto_now=True,
        help_text=(
            "Date and time when the table data was last updated in the system"
        )
    )

    # ---------------------------------------------------------------------------
    # Meta
    # ---------------------------------------------------------------------------
    class Meta:
        abstract = True

backend/base/forms.py
from django import forms
import logging

logger = logging.getLogger(__name__)


# -------------------------------------------------------------------------------
# BaseForm
# -------------------------------------------------------------------------------
class BaseForm(forms.Form):

    # ---------------------------------------------------------------------------
    # __init__
    # ---------------------------------------------------------------------------
    def __init__(self, *args, **kwargs):
        super(BaseForm, self).__init__(*args, **kwargs)

        # Add html attributes to support bootstrap controls
        for field_name in self.fields:
            try:
                if self.fields[field_name].widget.input_type == 'file':
                    self.fields[field_name].widget.attrs['class'] = \
                        'custom-file-input'

                elif self.fields[field_name].widget.input_type == 'checkbox':
                    self.fields[field_name].widget.attrs['class'] = \
                        'form-check-input'

                elif self.fields[field_name].widget.input_type == 'radio':
                    self.fields[field_name].widget.attrs['class'] = \
                        'form-check-input'

                elif isinstance(self.fields[field_name], forms.DateTimeField):
                    self.fields[field_name].widget.input_type = \
                        'datetime-local'

            except AttributeError:
                pass

backend/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--begin::Fonts-->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700" />
    <!--end::Fonts-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <title>{% block page-title %}
        Home
    {% endblock page-title%}
</title>
</head>
<body>

    <div class="container-fluid">
        {% include 'base/navbar.html' %}
        {% block body %}{% endblock %}
    </div>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    
</body>
</html>

backend/templates/base/navbar.html
{% block content %}

<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'account:dashboard' %}">{% if user.is_authenticated %}Hello {{user}} {% else %} Nav {% endif %}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'account:logout' %}">Logout</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'account:login' %}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" aria-current="page" href="{% url 'account:signup' %}">Signup</a>
          </li>
          {% endif %}
          
        </ul>
        <form class="d-flex" role="search">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>


  {% endblock content %}